load("@rules_python//python:defs.bzl", "py_test")

filegroup(
    name = "sources",
    srcs = glob(
        [
            "aws/**",
            "bootstrap/*.json",
        ],
        allow_empty = True,
    ) + [
        "//platform/environments:examples",
    ],
    visibility = ["//visibility:public"],
)

py_test(
    name = "unit_test",
    srcs = ["tests/test_infrastructure.py"],
    data = [":sources"],
    legacy_create_init = 0,
    main = "tests/test_infrastructure.py",
    tags = ["unit"],
)
